language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
matrix:
  include:
    - python: 3.5
      dist: trusty
install:
  - pip install -U setuptools pip
  - python setup.py clean --all
  - python setup.py install
script:
  - python -W all setup.py test
